openapi: 3.0.0
info:
  title: Controle de Investimento API
  version: 1.0.0
  description: Documentação da API para uma palicação que armazena e gerencia investimentos

paths:
  /api/investment:
    post:
      summary: Cria um novo investimento
      operationId: createInvestment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                value:
                  type: number
                created_at:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Investimento criado com sucesso
        '400':
          description: Dados inválidos. Tanto "name" quanto "value" são obrigatórios.

  /api/investments/listInvestments:
    get:
      summary: Lista investimentos paginados
      operationId: listInvestments
      parameters:
        - name: page
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            example: 1
        - name: perPage
          in: query
          description: Itens por página
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Lista de investimentos paginada
          content:
            application/json:
              example:
                investments:
                  - id: 1
                    value: 1000.00
                    createdAt: '2022-01-09 14:30:00'
                  - id: 2
                    value: 1500.50
                    createdAt: '2022-01-10 09:45:00'
                total: 2
        '400':
          description: Requisição inválida
          content:
            application/json:
              example:
                error: 'Parâmetros inválidos'

  /api/investment/{investmentId}:
    get:
      summary: Visualiza detalhes de um investimento
      operationId: viewInvestment
      parameters:
        - name: investmentId
          in: path
          description: ID do investimento
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes do investimento
        '404':
          description: Investimento não encontrado

  /api/investment/{investmentId}/withdraw:
    put:
      summary: Realiza saque de um investimento
      operationId: withdrawInvestment
      parameters:
        - name: investmentId
          in: path
          description: ID do investimento
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                additionalInfo:
                  type: string
                  description: Informações adicionais sobre o saque
      responses:
        '200':
          description: Saque realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  withdrawal_amount:
                    type: number
        '400':
          description: Falha ao realizar saque
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
      description: >
        Este endpoint permite realizar um saque de um investimento.
        O saque é calculado com base no saldo atual, ganhos acumulados, taxas, etc.<br>
        __Retirada__ de um investimento.<br>
        1. O saque será sempre a soma do valor inicial e seus ganhos,
          retirada parcial não é suportada.
        2. As retiradas podem acontecer no passado ou hoje, mas não podem acontecer antes da criação do investimento ou no futuro.

components:
  schemas:
    Investment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do investimento
        name:
          type: string
          description: Nome do investimento
        value:
          type: number
          format: double
          description: Valor do investimento
        created_at:
          type: string
          format: date-time
          description: Data e hora de criação do investimento        

    InvestmentDetails:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        amount:
          type: number
        earnings:
          type: number
        expected_balance:
          type: number
        withdrawal_amount:
          type: number
        days_invested:
          type: integer
        investment:
          $ref: '#/components/schemas/Investment'
          
    WithdrawalDetails:
      type: object
      properties:
        message:
          type: string
        withdrawal_amount:
          type: number
        additional_details:
          type: object
          properties:
            total_amount:
              type: number
            tax_rate:
              type: number
            earned_interest:
              type: number
            current_balance:
              type: number
